-- Seed careers (50+ with Holland codes)
-- Holland: R=Realistic, I=Investigative, A=Artistic, S=Social, E=Enterprising, C=Conventional

INSERT INTO careers (name, description, holland_codes, salary_min, salary_max) VALUES
('Software Engineer', 'Design and develop software applications and systems', ARRAY['I', 'R', 'C'], 80000, 180000),
('Mechanical Engineer', 'Design and build mechanical systems and machines', ARRAY['R', 'I', 'C'], 65000, 120000),
('Civil Engineer', 'Plan and oversee construction of infrastructure', ARRAY['R', 'I', 'C'], 65000, 110000),
('Electrical Engineer', 'Design electrical systems and equipment', ARRAY['R', 'I', 'C'], 70000, 130000),
('Data Scientist', 'Analyze data to extract insights and build models', ARRAY['I', 'C', 'E'], 90000, 180000),
('Physician', 'Diagnose and treat medical conditions', ARRAY['I', 'S', 'R'], 150000, 350000),
('Nurse', 'Provide patient care and support in healthcare settings', ARRAY['S', 'R', 'I'], 55000, 100000),
('Teacher', 'Educate students in various subjects', ARRAY['S', 'A', 'I'], 45000, 85000),
('Psychologist', 'Study and treat mental processes and behavior', ARRAY['I', 'S', 'A'], 60000, 130000),
('Social Worker', 'Help individuals and families overcome challenges', ARRAY['S', 'I', 'A'], 45000, 75000),
('Graphic Designer', 'Create visual content for brands and media', ARRAY['A', 'I', 'E'], 45000, 95000),
('Architect', 'Design buildings and structures', ARRAY['A', 'R', 'I'], 65000, 130000),
('Writer', 'Create written content across various mediums', ARRAY['A', 'I', 'S'], 40000, 120000),
('Musician', 'Create and perform music', ARRAY['A', 'S', 'E'], 30000, 150000),
('Photographer', 'Capture images for various purposes', ARRAY['A', 'R', 'E'], 35000, 90000),
('Marketing Manager', 'Develop and execute marketing strategies', ARRAY['E', 'A', 'S'], 70000, 150000),
('Sales Representative', 'Sell products and services to customers', ARRAY['E', 'S', 'C'], 45000, 120000),
('Entrepreneur', 'Start and run businesses', ARRAY['E', 'I', 'R'], 50000, 500000),
('Financial Analyst', 'Analyze financial data and trends', ARRAY['I', 'C', 'E'], 65000, 130000),
('Accountant', 'Manage financial records and prepare reports', ARRAY['C', 'I', 'E'], 50000, 95000),
('Lawyer', 'Provide legal advice and represent clients', ARRAY['E', 'I', 'S'], 80000, 200000),
('HR Manager', 'Oversee human resources and recruitment', ARRAY['S', 'E', 'C'], 65000, 130000),
('Project Manager', 'Plan and execute projects', ARRAY['E', 'C', 'S'], 75000, 140000),
('Chef', 'Prepare and create culinary dishes', ARRAY['R', 'A', 'E'], 40000, 90000),
('Veterinarian', 'Care for animal health', ARRAY['I', 'R', 'S'], 80000, 160000),
('Dentist', 'Diagnose and treat dental conditions', ARRAY['R', 'I', 'S'], 120000, 220000),
('Pharmacist', 'Dispense medications and advise on usage', ARRAY['I', 'C', 'S'], 110000, 150000),
('Physical Therapist', 'Help patients recover mobility and function', ARRAY['S', 'R', 'I'], 65000, 100000),
('Biologist', 'Study living organisms', ARRAY['I', 'R', 'C'], 55000, 110000),
('Chemist', 'Research and analyze chemical substances', ARRAY['I', 'R', 'C'], 60000, 120000),
('Environmental Scientist', 'Study and protect the environment', ARRAY['I', 'R', 'S'], 55000, 110000),
('Pilot', 'Operate aircraft', ARRAY['R', 'I', 'C'], 80000, 200000),
('Electrician', 'Install and maintain electrical systems', ARRAY['R', 'I', 'C'], 50000, 90000),
('Plumber', 'Install and repair plumbing systems', ARRAY['R', 'I', 'C'], 45000, 85000),
('Web Developer', 'Build and maintain websites', ARRAY['I', 'A', 'R'], 55000, 130000),
('UX Designer', 'Design user experiences for products', ARRAY['A', 'I', 'S'], 70000, 140000),
('Game Developer', 'Create video games', ARRAY['I', 'A', 'R'], 60000, 150000),
('Journalist', 'Research and report news', ARRAY['A', 'I', 'S'], 40000, 95000),
('Film Director', 'Direct film and video productions', ARRAY['A', 'E', 'S'], 50000, 500000),
('Fashion Designer', 'Create clothing and accessories', ARRAY['A', 'E', 'I'], 45000, 120000),
('Interior Designer', 'Design interior spaces', ARRAY['A', 'E', 'R'], 45000, 95000),
('Real Estate Agent', 'Help clients buy and sell property', ARRAY['E', 'S', 'C'], 40000, 150000),
('Management Consultant', 'Advise organizations on strategy', ARRAY['E', 'I', 'S'], 80000, 200000),
('Investment Banker', 'Advise on financial transactions', ARRAY['E', 'I', 'C'], 100000, 300000),
('Actuary', 'Assess financial risk using mathematics', ARRAY['I', 'C', 'E'], 80000, 150000),
('Librarian', 'Organize and manage information resources', ARRAY['C', 'S', 'I'], 45000, 75000),
('Paralegal', 'Support lawyers with legal work', ARRAY['C', 'I', 'E'], 45000, 75000),
('Administrative Assistant', 'Support office operations', ARRAY['C', 'S', 'E'], 35000, 60000),
('Police Officer', 'Enforce laws and protect communities', ARRAY['R', 'S', 'E'], 50000, 95000),
('Firefighter', 'Respond to emergencies and fight fires', ARRAY['R', 'S', 'I'], 45000, 85000),
('Military Officer', 'Lead and manage military operations', ARRAY['E', 'R', 'S'], 50000, 120000),
('Translator', 'Convert text between languages', ARRAY['A', 'I', 'C'], 45000, 90000),
('Event Planner', 'Organize and coordinate events', ARRAY['E', 'S', 'A'], 45000, 85000);

-- Seed majors (40+ with Holland codes)
INSERT INTO majors (name, description, holland_codes, related_careers) VALUES
('Computer Science', 'Study of computation and programming', ARRAY['I', 'R', 'C'], ARRAY['Software Engineer', 'Data Scientist', 'Web Developer', 'Game Developer']),
('Mechanical Engineering', 'Design and analysis of mechanical systems', ARRAY['R', 'I', 'C'], ARRAY['Mechanical Engineer', 'Aerospace Engineer']),
('Civil Engineering', 'Design of infrastructure and construction', ARRAY['R', 'I', 'C'], ARRAY['Civil Engineer', 'Structural Engineer']),
('Electrical Engineering', 'Study of electrical systems', ARRAY['R', 'I', 'C'], ARRAY['Electrical Engineer', 'Software Engineer']),
('Biology', 'Study of living organisms', ARRAY['I', 'R', 'C'], ARRAY['Biologist', 'Veterinarian', 'Physician']),
('Chemistry', 'Study of matter and its properties', ARRAY['I', 'R', 'C'], ARRAY['Chemist', 'Pharmacist', 'Environmental Scientist']),
('Psychology', 'Study of mind and behavior', ARRAY['I', 'S', 'A'], ARRAY['Psychologist', 'Social Worker', 'Counselor']),
('Nursing', 'Healthcare and patient care', ARRAY['S', 'R', 'I'], ARRAY['Nurse', 'Healthcare Administrator']),
('Education', 'Teaching and learning methods', ARRAY['S', 'A', 'I'], ARRAY['Teacher', 'School Administrator']),
('English', 'Literature and writing', ARRAY['A', 'I', 'S'], ARRAY['Writer', 'Journalist', 'Editor']),
('History', 'Study of past events', ARRAY['I', 'A', 'S'], ARRAY['Historian', 'Teacher', 'Researcher']),
('Political Science', 'Study of government and politics', ARRAY['I', 'E', 'S'], ARRAY['Lawyer', 'Policy Analyst', 'Politician']),
('Economics', 'Study of markets and resources', ARRAY['I', 'E', 'C'], ARRAY['Financial Analyst', 'Economist', 'Consultant']),
('Business Administration', 'Management and business operations', ARRAY['E', 'C', 'S'], ARRAY['Manager', 'Entrepreneur', 'Consultant']),
('Finance', 'Financial systems and investments', ARRAY['E', 'I', 'C'], ARRAY['Financial Analyst', 'Investment Banker', 'Accountant']),
('Accounting', 'Financial record keeping', ARRAY['C', 'I', 'E'], ARRAY['Accountant', 'Auditor', 'Financial Analyst']),
('Marketing', 'Promotion and brand management', ARRAY['E', 'A', 'S'], ARRAY['Marketing Manager', 'Brand Manager']),
('Graphic Design', 'Visual communication design', ARRAY['A', 'I', 'E'], ARRAY['Graphic Designer', 'UX Designer']),
('Fine Arts', 'Studio art and creative expression', ARRAY['A', 'I', 'S'], ARRAY['Artist', 'Illustrator', 'Photographer']),
('Music', 'Music theory and performance', ARRAY['A', 'S', 'E'], ARRAY['Musician', 'Music Producer', 'Composer']),
('Film Studies', 'Cinema and media production', ARRAY['A', 'I', 'E'], ARRAY['Film Director', 'Video Editor', 'Producer']),
('Architecture', 'Building design', ARRAY['A', 'R', 'I'], ARRAY['Architect', 'Urban Planner']),
('Communications', 'Media and message delivery', ARRAY['A', 'S', 'E'], ARRAY['Journalist', 'PR Specialist', 'Writer']),
('Sociology', 'Study of society and social behavior', ARRAY['I', 'S', 'A'], ARRAY['Social Worker', 'Researcher', 'Policy Analyst']),
('Mathematics', 'Abstract structures and logic', ARRAY['I', 'C', 'R'], ARRAY['Data Scientist', 'Actuary', 'Statistician']),
('Physics', 'Study of matter and energy', ARRAY['I', 'R', 'C'], ARRAY['Physicist', 'Engineer', 'Researcher']),
('Environmental Science', 'Study of environment and sustainability', ARRAY['I', 'R', 'S'], ARRAY['Environmental Scientist', 'Conservationist']),
('Pre-Med', 'Preparation for medical school', ARRAY['I', 'S', 'R'], ARRAY['Physician', 'Surgeon', 'Dentist']),
('Pre-Law', 'Preparation for law school', ARRAY['E', 'I', 'S'], ARRAY['Lawyer', 'Judge', 'Legal Advisor']),
('Criminal Justice', 'Study of law enforcement and legal systems', ARRAY['R', 'S', 'E'], ARRAY['Police Officer', 'Lawyer', 'Probation Officer']),
('Human Resources', 'Personnel management', ARRAY['S', 'E', 'C'], ARRAY['HR Manager', 'Recruiter']),
('Information Technology', 'Computer systems and networks', ARRAY['I', 'C', 'R'], ARRAY['IT Specialist', 'Systems Administrator']),
('Data Science', 'Data analysis and machine learning', ARRAY['I', 'C', 'E'], ARRAY['Data Scientist', 'Analyst']),
('Neuroscience', 'Study of the nervous system', ARRAY['I', 'R', 'S'], ARRAY['Neuroscientist', 'Researcher', 'Physician']),
('Philosophy', 'Study of fundamental questions', ARRAY['I', 'A', 'S'], ARRAY['Professor', 'Writer', 'Ethicist']),
('Anthropology', 'Study of human societies', ARRAY['I', 'S', 'A'], ARRAY['Anthropologist', 'Researcher', 'Museum Curator']),
('International Relations', 'Study of global politics', ARRAY['I', 'E', 'S'], ARRAY['Diplomat', 'Policy Analyst', 'NGO Worker']),
('Fashion Design', 'Clothing and accessory design', ARRAY['A', 'E', 'I'], ARRAY['Fashion Designer', 'Stylist']),
('Culinary Arts', 'Food preparation and hospitality', ARRAY['R', 'A', 'E'], ARRAY['Chef', 'Restaurant Manager']),
('Sports Management', 'Business of sports', ARRAY['E', 'S', 'C'], ARRAY['Sports Agent', 'Athletic Director']);
